language: python

python:
  - "2.7"
  - "pypy"

env:
  - CODECLIMATE_REPO_TOKEN=d1bca6bdad77d55f4fa2b299d6478dc325c68729a1a7e64d148fb1281fb5439d

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

script:
  - THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  - export PYTHONPATH=$THIS_DIR:$PYTHONPATH
  - python setup.py test
  - codeclimate-test-reporter

sudo: false
